services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook
    container_name: notebook
    ports:
      - 8888:8888
      - 4040:4040
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
