services:
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: notebook
    ports:
      - "8888:8888"
    # volumes:
      # - ./notebooks:/home/jovyan/work
      # - /home/sebin/programming/python/test_spark/notebooks:/home/jovyan/work
    user: root
    environment:
      GRANT_SUDO: "yes"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
