services:
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    # user: root
    # environment:
      # - GRANT_SUDO=yes
      # - NB_USER=jupyternb
      # - NB_UID=1000
      # - NB_GID=100
      # - CHOWN_HOME=yes
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
